[package]
name = "tiny-cli"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[[bin]]
name = "tiny"
path = "src/main.rs"

[dependencies]
tiny-library = { path = "../tiny-library" }
rustyline = "13.0.0"
anyhow = "1.0.76"
